#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const express = require('express');
const fileUpload = require('express-fileupload');
const app = express();
const PORT = process.env.PORT || 3000;

const conducts = require('./routes/conducts.js');
const index = require('./routes/index.js');

app.use(fileUpload());
app.use(express.static(path.join(__dirname, 'public')));
app.use('/api', index);
app.use('/api/conducts', conducts);

app.listen(PORT, () => {
  console.log('app listening on port ' + PORT + '!');
});
